services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    container_name: board-database
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password0
    expose:
      - "1433"

  web:
    build:
      context: ./
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    image: board_web
    container_name: board-web
    restart: always
    depends_on:
      - database
    ports:
      - "${WEB_PORT:-5000}:5000"
    volumes:
      - .:/app
